### ISSUE TITLE
Frontend fehlt als requirement

### ISSUE THREAD

**Issue by hansmorb** [inSPEYERed/cb-statistics#1]
Das Paket frontend kommt nicht standardmäßig mit Python3 mit

**Comment by Splines** [comment]
Hi, ich habe von diesem Paket noch nie etwas gehört. Wenn du mit `pip install -r requirements.txt` die requirements installierst, sollten ja eigentlich auch die Sub-Dependencies mit installiert werden von `matplotlib`, `numpy` etc. Hättest du noch die genaue Fehlermeldung für mich, bitte?

**Comment by hansmorb** [comment]
Leider nicht mehr, Es war der klassische ImportError No Module named frontend Fehler.

Die requirements habe ich vorher mit dem obigen Kommando installiert.

**Comment by Splines** [comment]
Could not reproduce this issue with a freshly cloned repository and a virtual environment. These are my steps:

```
git clone https://github.com/inSPEYERed/cb-statistics.git
cd ./cb-statistics/
python -m venv .venv
./venv/Scripts/activate
python -m pip install --upgrade pip
pip install -r ./requirements.txt
python ./src/main.py
```

Please add an error log if you still encounter this issue, otherwise closed as not reproducible.
